name: Rolls-Royce CI Workflow

on:
  pull_request:
    branches: [ main ]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build --info
      - name: check gradle
        run: ./gradlew check
      - name: codecov gradle
        run: ./gradlew jacocoTestReport
      - name: codecov upload
        run: bash <(curl -s https://codecov.io/bash)
